// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdo4xwdr0bm4LMxbYcBLPswVcwy0WzARg',
    appId: '1:1068862293740:web:28895b65ee234307f6c7c9',
    messagingSenderId: '1068862293740',
    projectId: 'boaz--nutrition-calculator',
    authDomain: 'boaz--nutrition-calculator.firebaseapp.com',
    storageBucket: 'boaz--nutrition-calculator.appspot.com',
    measurementId: 'G-MGYVYQ4CN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxlBzK-vPCozmeNA9jdwdfpiDYvFiVKU',
    appId: '1:1068862293740:android:416083ae5e29adeef6c7c9',
    messagingSenderId: '1068862293740',
    projectId: 'boaz--nutrition-calculator',
    storageBucket: 'boaz--nutrition-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKLQXcf1wq5gKkJ9Y1ckwrQ83cZWmZzw',
    appId: '1:1068862293740:ios:d527ac32f936d590f6c7c9',
    messagingSenderId: '1068862293740',
    projectId: 'boaz--nutrition-calculator',
    storageBucket: 'boaz--nutrition-calculator.appspot.com',
    iosClientId: '1068862293740-p242i4mehou0k8rg9g9pa1uei762uk53.apps.googleusercontent.com',
    iosBundleId: 'com.tanjadejong.boazNutritionCalculator',
  );
}
